Makefile
scripts/pyodide_packages.py
src/scripts/shinylive.py

This PR, along with https://github.com/rstudio/py-shiny/pull/310, make it so that when a user runs `shiny static`, it calls out to code in shinylive to do the deployment, instead of the previous method, which was to do the deployment from code within the shiny package. More information in that PR.

Handle deployments, and deployments only include necessary packages.

---

examples/reactive_value/app.py

A minor update with the replacement of the wrong reactive function name with a proper one in the comments.

Fix reactive function name

---

src/Components/App.css
src/Components/Terminal.css
src/Components/Terminal.tsx

Also, I noticed that Source Sans Pro is being used but it doesn't look like the Google font is being loaded, so it'll look like Arial/Helvetica unless you happen to have the font installed locally.

Use Consolas and Liberation Mono for monospace on Windows and Linux

---

package.json
scripts/build.ts
yarn.lock

While experimenting with my shinylive/webR fork I hit [an issue with esbuild](https://github.com/evanw/esbuild/issues/2851). The issue does not affect Pyodide, but I have upgraded esbuild in my fork to avoid the bug and thought it might be a good idea to upstream the change. So, this PR upgrades esbuild from v0.16.17 to v0.17.19.
As described in the [esbuild release notes for v0.17](https://github.com/evanw/esbuild/releases/tag/v0.17.0), there is a breaking change in the `.build()` and `.serve()` API, so the shinylive `build.ts` script needed to be re-written for the upgrade.
I replaced the calls to `esbuild.build()` with the newer async `esbuild.context()` API, replaced the `watchProps` property with calls to `.watch()` for each esbuild context, and updated the `.serve()` call to use the …

Update esbuild to v0.17 and rewrite `build.ts` for the new API

---

Makefile
README.md

The first time I ran the command `make all` it threw an error
```sh
yarn
make: yarn: No such file or directory
make: *** [node_modules] Error 1
```
This was because `yarn` wasn't installed on the machine and it was required for installing other packages.
Create a variable in the makefile that checks if `yarn` exists on the machine, if not it will install it.
It can probably be optimized by only invoking it when `node_modules` target is invoked.
Removed `node_modules` -> `npm uninstall -g yarn` -> Run `make node_modules`. Check log to contain
```sh
➜  shinylive git:(main) make node_modules
Yarn is not installed. Installing...
yarn
```
After `yarn` is already installed, run `make node_modules` -> Check the logs to see if yarn wasn't installed again.
```sh
make node_modules
yarn
```

chore: Add step to install yarn in Makefile

---

examples/orbit/app.py
examples/orbit/body.py

UI changes:
1. Use fillable plot output for simulation plot
2. Tuck direction diagram into the bottom-right corner (and hide it on smaller screen sizes)
3. Use sidebar layout
4. Put earth, moon, planetx into accordion
Code change:
1. Use Shiny modules for earth/moon/planetx
2. Separate simulation logic from plotting logic

Apply Greg styling suggestions to orbit; use modules

---

package.json
src/Components/App.tsx
src/hooks/useWebR.tsx
src/webr-proxy.ts
yarn.lock

* Updates webR to v0.2.1.
* Ensure webR is ready before starting the async loop to handle webR output.
* If the loading page is not Cross Origin Isolated (COI), rather than redirecting to `?coi=1`, instead use webR's fallback `PostMessage` channel type.
The (newly added to 0.2.1) `PostMessage` channel for webR does not rely on blocking the worker's event loop. As such, it will work better when loading both Shiny for R and Shiny for Python apps on the same page, and also in environments where COI is not possible, such as in the integrated VS Code browser.
R tools that rely on generating a nested prompt, such as `readline()` and `browser()`, won't work[1]. I expect these won't be needed much for Shiny apps, but if a user would really like to use them, they just need to serve the page with …

Upgrade to webr@0.2.1 and fix Shiny for R in VS Code browser

---

src/run-python-blocks.ts

This closes #60.
This is the HTML structure that shinylive expects:
```html
<pre class="shinylive-r" data-engine="r"><code>#\| standalone: true
...
```
Shinylive searches for elements with `class="shinylive-r"`, and then looks at the `data-engine` attribute on that element.
However, the RevealJS format for Quarto transforms it into this:
```html
<div class="sourceCode" id="cb2" data-engine="r">
<pre class="sourceCode numberSource shinylive-r number-lines code-with-copy">
<code class="sourceCode">
<span id="cb2-1"><a href="#cb2-1"></a>#\| standalone: true</span>
...
```
Note that the `data-engine` attribute is no longer in the same element as `class="shinylive-r"`.
This PR makes it so that it will look for `data-engine` in both the `class="shinylive-r"` element, and the immediate parent.
I …

Look for `data-engine` attribute in parent element

---

src/Components/Editor.tsx
src/language-server/null-client.ts

This PR adds a new "null" LSP client. The LSP client starts up, but does nothing. Writing out messages is ignored and incoming messages are never generated.
The idea here is rather than conditionally executing code in many places related to setting up and using the pyright LSP, we can instead create a dummy LSP that does nothing for use when running R Shiny apps.
Later, we can add a new R LSP client class and switch to using that for R apps instead.
Such a null LSP client might also be useful in the future as part of an abstract client that delegates messages to the various LSP servers we eventually support, with the null client as a fallback to quietly handle file types where there is no LSP server.
With this change, shinylive should no longer try to read any files from `/pyright` or …

Add a null LSP client for use when not running Python apps

---

src/Components/HeaderBar.tsx
src/parse-codeblock.ts
src/scripts/codeblock-to-json.ts
src/utils.ts

Pass in `engine` as first `arg` to `codeblock-to-json.js` so that quarto extension can tell which language is being used.

Determine engine from first arg in codeblock-to-json.ts

---

Makefile
package.json
src/hooks/useWebR.tsx
src/messageporthttp.ts
src/webr-proxy.ts
yarn.lock

As in #80, but without loading the R Shiny package and dependencies as a filesystem image.
Instead, R packages continue to be loaded from CDN as before.

Upgrade webR to v0.2.2

---

.gitignore
examples/python/app_with_plot/app.py
examples/python/basic_app/app.py
examples/python/cpuinfo/app.py
examples/python/cpuinfo/helpers.py
examples/python/regularization/app.py

This translates a couple of apps to express. I'm going to do small PRs into the `rc-express` branch so that review is less of a big deal. 
Tracking ticket: https://github.com/posit-dev/py-shiny/issues/995

Expressify Python apps #1

---

examples/python/ipyleaflet/app.py
examples/python/ipywidgets/app.py
examples/python/ipywidgets/requirements.txt
examples/python/output_ui/app.py
examples/python/plotly/app.py

I mostly included the  apps from the new ipywidget docs. One bit that might need a callout is the `render.express` example. I wanted something which returned a context manager, and iterator, and a rendering function, and to do that I needed to be explicit aobut the output. This is basically a module workaround, but I think it's a pretty good example of what `render.express`can do. 
```
from shiny import render
from shiny.express import ui, input, output
import numpy as np
import matplotlib.pyplot as plt
ui.input_slider("n", "Number of cards", value=3, min=1, max=5)
@render.express
def cards():
with ui.layout_columns():
for i in range(input.n()):
with ui.card():
f"Card {i}"
@output(id=f"hist_{i}")
@render.plot(alt="A histogram")
def histogram():
np.random.seed(19680801)
x = 100 + 15 * …
```

Expressify shiny widgets

---

scripts/build.ts
src/messageporthttp.ts
src/shinylive-sw.ts

See https://github.com/posit-dev/r-shinylive/issues/51#issuecomment-1923433562 and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#directives) for details.
With this change, cross-origin requests for embedded content are sent without credentials and so the responses are allowed without an explicit permission via the CORP header in the response. This fixes embedding certain types of content in webR Shinylive apps, while still allowing the option of using cross-origin isolation and `SharedArrayBuffer` with webR.
Fixes https://github.com/posit-dev/r-shinylive/issues/49 (embedding MathJax) and https://github.com/posit-dev/r-shinylive/issues/51 (embedding openstreetmap)

Switch COEP header from `require-corp` to `credentialless`

---

.github/workflows/build.yml

With this, the content type for the file `library.data` is set to `"application/wasm"` in S3. CloudFront compresses files with such content-type using GZIP encoding over the wire.
Update: Due to AWS file-size limits on automatic GZIP compression I've updated the PR so that `library.data` is compressed at the S3 source. The browser still decompresses on the fly.

S3: Set content-type for Shiny for R library.data

---

package-lock.json
package.json
scripts/build.ts
site_template/editor/index.html
site_template/examples/index.html
src/Components/App.tsx
src/Components/Editor.tsx
src/Components/share.ts
src/lzstring-worker.ts

This closes #128. When the user presses the play button, it will automatically update the URL hash.
The encoding is done in a web worker, so it will not block the main thread.
A few remaining tasks:

Update browser URL hash when user presses play button

---

src/Components/Viewer.tsx
src/hooks/useWebR.tsx

Pairs with https://github.com/rstudio/shiny/pull/4073
When `devMode` is `true`, we set `shiny.client_devmode = TRUE` to turn on client-side developer features like the error console.

feat: enable client-side dev mode features in R

---

src/Components/App.tsx
src/Components/utils.ts

* Fixes https://github.com/quarto-ext/shinylive/issues/36
Adds a utility function, `asCssLengthUnit()`, that promotes numbers to pixels or otherwise passes through a string value. This enables `viewerHeight: 300` → `300px` as in the current behavior or `viewerHeight: 300px` (or any other CSS unit).

feat: Allow CSS units in `viewerHeight` option

---

src/Components/Editor.tsx

This PR adds two common and highly popular keybindings to the editor for the R app engine:
* <kbd>Alt/Opt</kbd> + <kbd>-</kbd>: Assignment operator `<-`
* <kbd>Ctrl/Cmd</kbd> + <kbd>Shift</kbd>  + <kbd>M</kbd>: Pipe operator `|>`
Given that r-wasm works with R >= 4.3, I think it's fair to use the base-R pipe operator and not worth the additional effort required to make the keybinding configurable.
The keybindings take care to only add a leading and trailing space when there isn't already space around the current cursor position.
https://github.com/posit-dev/shinylive/assets/5420529/36953102-9ca5-4977-a24b-6b592c08870b

feat: Add assignment and pipe keybindings

---

src/Components/App.css
src/Components/App.tsx
src/Components/Editor.tsx
src/Components/ResizableGrid/ResizableGrid.tsx
src/Components/utils.ts

* Fixes https://github.com/quarto-ext/shinylive/issues/33
This PR builds on #140 to incorporate an `editorHeight` option. Editor height has the same semantics as `viewerHeight` (hence the dependency on #140), where users can provide a numeric value taken as pixels or a string, taken as a CSS value.
I updated the following layouts to use `editorHeight`
1. `editor-viewer`
* In a vertical layout, `editorHeight` and `viewerHeight` are supplied to `grid-template-rows`. In other words, the editor and viewer are independently sized. The default value is `auto, 200px` (editor, viewer).
* In a horizontal layout, the editor and viewer are next to each other. In this case, setting either `editorHeight` or `viewerHeight` can constrain the overall height of the component. If both are set (to values …

feat: Add `editorHeight` option

---

export_template/edit/index.html
export_template/index.html
src/Components/App.tsx

This PR consolidates the JavaScript for launching an exported shiny app into `runExportedApp()` to avoid duplicating logic between the `index.html` template file and `edit/index.html`:
* Adds `{{title}}` as a template parameter.
* Consolidate app-launching code in `runExportedApp()`.
* Pick up app mode from the `mode` query parameter.
* `edit/index.html` now redirects to `index.html?mode=editor-terminal-viewer`.
* Adds template parameters for additional content:
* `{{{include_in_head}}}` for content just before `</head>`
* `{{{include_before_body}}}` for content just after `<body>`
* `{{{include_after_body}}}` for content just before `</body>`
These changes are intended to help with
* https://github.com/posit-dev/r-shinylive/issues/32#issuecomment-2195013283
* …

feat: Restructure and expand `export_template` files

---

src/hooks/useWebR.tsx

Fixes #90
From https://github.com/posit-dev/r-shinylive/issues/45
Sets `R_CONFIG_ACTIVE` environment variable to `"shinylive"`. This is similar to the value set [in Posit Connect and Cloud](https://rstudio.github.io/config/articles/rsconnect.html) and will let app authors more easily include logic or change configuration settings to target shinylive settings.

feat(shinylive-r): Set `R_CONFIG_ACTIVE` envvar

---

src/Components/App.tsx
src/Components/Editor.css

A small change to add `.layout-vertical` or `.layout-horizontal` to the `.editor-viewer` container depending on the app layout.
We then use this class to only limit the editor height to 800px when in `.layout-vertical`. Otherwise the editor is not resizable vertically and this limitation artificially constrains the editor height.

feat: Add `layout-${layout}` class to `editor-viewer` mode

---

export_template/edit/index.html
src/Components/App.tsx

Uses `_shinylive-mode` instead of plain `mode` to make it easier to identify shinylive query string parameters and to stay out of the way of app params if #79 is completed in the future.

chore: Use `_shinylive-mode` for query parameter in exported apps

---

src/shinylive-sw.ts

When we're not intercepting a Wasm app URL and not adding COI headers to a request, we can avoid a (potentially many MB) copy in the service worker by not intercepting the request at all.
This should reduce noise in the Network tab of web browsers' devtools, and provide a minor performance boost when fetching additional content for webR, such as `.../cairo.so`

Avoid intercepting network requests in the service worker when we don't need to

---

Makefile

Github Pages supports serving content with HTTP status 206, "Partial Content", but content that is served in this way is not cached by the brower (at least, not by Chrome). So, when using Shinylive hosted on GitHub Pages multiple (slow!) network requests are sent on every page load for the webR resource file `cairo.so`, even if the file has already been previously downloaded by the browser.
Emscripten is configured to fetch lazy filesystem content with size greater than 1MB in chunks, using the partial content mechanism. The chunk size is hard coded [here](https://github.com/emscripten-core/emscripten/blob/ec14ddf11ac3bc594aa9b75a8633e5f22aa84cd4/src/library_fs.js#L1694) and I can't see a way to disable things. We might be able to submit a PR to Emscripten implementing such a disable …

Avoid Partial Content HTTP download in webR, fixing browser caching for `cairo.so`

---

src/messageporthttp.ts

This was a workaround required for constructing new R atomic vectors in older versions of webR, and is no longer required anymore.
Fixes #148.

Don't convert an `Uint8Array` object to an `Array` when creating R raw vectors

---

examples/python/cpuinfo/app.py

Fixes an error:
```
AttributeError: 'ColormapRegistry' object has no attribute 'get_cmap'
```
that happens on the Heatmap tab of the cpuinfo example. We can undo this when we upgrade pyodide and get newer versions of matplotlib/pandas.

Fix cmap issue between matplotlib and pandas

---

scripts/build.ts
shinylive_lock.json
shinylive_requirements.json
src/hooks/usePyodide.tsx

Recent versions of Pyodide come with IPython 8.23.0. Previous versions did not, and we needed to shim in a stub for IPython. This PR makes it use the Pyodide version of IPython. It also removes an entry in shinylive_lock.json that should not have been there (and didn't have an effect anyway, because our IPython shims took precedence over this entry.)
@cpsievert It might be worthwhile to run `make update_packages_lock` and see if anything breaks.

Use Pyodide's version of IPython

---

src/Components/App.tsx
src/hooks/useRunOnceOnMount.tsx

If there is a parent window, the `App` will now post a message to the parent when it is ready.
Notes:
- Currently, "ready" means that it is ready to receive `setFiles` messages posted to the this window, but conceivably one might want to have signals of other events (like when the app actually starts running), so it might make sense to have a message type that can represent multiple types of events.

Post message to parent when ready

---

src/hooks/useWebR.tsx

A first step in handling https://github.com/quarto-ext/shinylive/issues/59.
This wraps the mounting of bundled Wasm R packages in a `try()`, so that if something goes wrong (e.g. the `.data` file is not there for whatever reason) we recover and continue without the package, and try to start the Shiny app anyway.
This will likely be OK, since the missing package will instead be picked up from the public https://repo.r-wasm.org repo when (and if) it is actually used, which was always intended to be the fallback mode for when a required package is not included in the bundled Wasm assets.
Closes #163.

webR: Continue initialisation even if package mounting fails

---

Makefile

* [4ff1c65](https://github.com/posit-dev/shinylive/pull/172/commits/4ff1c6588ff833260252b10999b6b71852e160ff) reproduces the CI failure we're seeing on `py-shiny` -- `make all` now fails with the recent switch to `pyproject.toml`.
* [78b86a0](https://github.com/posit-dev/shinylive/pull/172/commits/78b86a0e73da1ebef66e5862aecc7f67fdefd859) proposes a fix. Note that this fix will only work for the latest dev version of Shiny.

Update to dev shiny and htmltools

---

site_template/app/index.html
site_template/editor/index.html
src/Components/App.tsx
src/Components/Viewer.tsx

For the `editor/` and `app/` pages, the window title now changes depending on the Viewer iframe's title (this is the Shiny app's title).
- If the title for the Shiny app is "Calculator":
- For the `editor/` page, the window title will now be "Shiny - Calculator".
- For the `app/` page, the window title will now be "Calculator".
- If the title for the Shiny app is not set, or the empty string:
- For the `editor/` page, the window title will now be "Shiny editor".
- For the `app/` page, the window title will now be "Shiny App".

Set title of window from Shiny app title

---

shinylive_lock.json

Updates shinyswatch to v0.8.0, fixing issues that were broken by the shiny v1.2.0 release.

chore: Update shinyswatch to v0.8.0

---

examples/r/003-reactivity/app.R

fix(examples): Don't repeat `caption` ID

---

src/parse-codeblock.ts

See https://github.com/quarto-dev/quarto/issues/368 for context.
Both `black` and `ruff format` (and others) add spaces after single `#` starting a comment, so `#|` becomes `# |`. The Quarto VS Code extension supports formatting inside Python code chunks, so in general Quarto also supports `# |` for it's code cell metadata syntax.
<table>
<tr>
<th>Before</th>
<th>Formatted</th>
</tr>
<tr>
<td><pre><code>
#| test: one
##| test: three</code></pre></td>
<td><pre><code>
##| test: three</code></pre></td>
</tr>
</table>
In https://github.com/quarto-dev/quarto/issues/368#issuecomment-2596098504 I proposed Quarto also support `##|`, since the formatters don't mess with that. I included support for that here, considering we already use `## file:`.

feat: Support `#|`, `# |` and `##|` for quarto metadata comment indicators

---

src/hooks/usePyodide.tsx

This PR changes shinylive to use the `pyodide_http.patch_all()`, which allows us to remove the custom shim for loading Seaborn data.

Use `pyodide_http.patch_all()` and remove custom Seaborn data shim

---

src/hooks/usePyodide.tsx

Related: https://github.com/posit-dev/py-shiny/issues/1914
Related: https://github.com/posit-dev/py-shiny/issues/1956
--------------
Q: Should [R shiny](https://github.com/posit-dev/shinylive/blob/0ca09681baf8116307e952935c62a3a5ec44452b/src/hooks/useWebR.tsx#L149) also have it's server-side bookmarking disabled?
* Can R perform server-side bookmarking?
Q: This might get the app to have bookmarking... but what about forwarding any query string values to the parent frame for shinylive.io? If the same answer as r-shiny is... not at the top of the priority queue... then we can wait until later!
TODO:

feat: Disable server-side bookmarking for py-shiny

---

.github/workflows/build.yml
Makefile
package-lock.json
package.json
src/hooks/useWebR.tsx
src/shinylive-sw.ts

* Upgrade webR to version v0.5.5 (R 4.5.1).
* Upgrade embedded R Shiny to v1.11.1.
* Update service worker injected COI headers, fixing CURL with webR in Safari.
The changes to the service worker only apply when the `?coi=1` query parameter is used with Shinylive. This is an undocumented (IIRC) feature required for using `browser()` (and now also CURL) in webR on Safari. The feature is disabled by default, and not many users are relying on it, so it should be fairly safe to tweak.

Upgrade webR to v0.5.5
